version: "2.1"
services:
  privateforge-pm5:
    image: eyp/privateforge:5
    build: ./privateforge/
    restart: always
    expose:
      - 8080
    volumes:
      - forge-data:/var/forge/modules
    networks:
      pm5net:
        aliases:
          - privateforge
  instance_demo-pm5:
    image: eyp/pupppetmaster:5
    build: ./puppetmaster5
    restart: always
    #[[remote_ip:]remote_port[-remote_port]:]port[/protocol]
    ports:
      - 8141:8140/tcp
    networks:
      pm5net:
        aliases:
          - instance_demo
    volumes:
      - pm-conf:/etc/puppetlabs

volumes:
  forge-data:
  pm-conf:

networks:
  pm5net:
    driver: overlay
