version: "2.1"
services:
  puppetdb:
    image: eyp/puppetdb:5
    build: ./puppetdb/
    restart: always
    ports:
      - 9141:8080/tcp
    volumes:
      - puppetdb-data:/tmp/puppetdb
    networks:
      pm5net:
        aliases:
          - puppetdb
          - puppetdb.pm5.docker
    environment:
      EYP_PUPPETFQDN: 'puppet5'
      EYP_PUPPETDB_EXTERNAL_PORT: '9141'
    healthcheck:
      test: ["CMD", "/bin/true"]
      interval: 30s
      timeout: 10s
      retries: 5
  puppetmaster:
    image: eyp/pupppetmaster:5
    build: ./puppetmaster5
    restart: always
    depends_on:
      puppetdb:
        condition: service_healthy
    ports:
      - 8141:8140/tcp
    environment:
      EYP_PUPPETFQDN: 'puppet5'
      EYP_PM_SSL_REPO: ''
      EYP_PM_CUSTOMER_REPO: ''
    networks:
      pm5net:
        aliases:
          - puppet5
          - puppet5.pm5.docker
    volumes:
      - ./ssh:/root/.ssh:ro
      - ./utils:/opt/utils:ro
    healthcheck:
      test: ["CMD", "curl", "--insecure", "https://localhost:8140"]
      interval: 60s
      timeout: 10s
      retries: 10

volumes:
  puppetdb-data:

networks:
  pm5net:
    driver: bridge
