version: "3.2"
services:
  privateforge-pm5:
    image: eyp/privateforge:5
    build: ./privateforge/
    restart: always
    expose:
      - 8080
    volumes:
      - type: volume
        source: forge-data
        target: /var/forge/modules
        volume:
          nocopy: false
    networks:
      pm5net:
        aliases:
          - privateforge
  instance_demo-pm5:
    image: eyp/pupppetmaster:5
    build: ./puppetmaster5
    restart: always
    ports:
      - target: 8141
        published: 8140
        protocol: tcp
        mode: ingress
    networks:
      pm5net:
        aliases:
          - instance_demo
    volumes:
      - type: volume
        source: logs
        target: /var/log/puppetlabs
        volume:
          nocopy: true
      - type: volume
        source: pm-conf
        target: /etc/puppetlabs
        volume:
          nocopy: false

volumes:
  forge-data:
  pm-conf:

networks:
  pm5net:
    driver: overlay
    attachable: true
