version: "2.1"
services:
  elasticsearch-pm5:
    image: eyp/elasticsearch:5
    build: ./elasticsearch/
    restart: always
    expose:
      - 9200
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch
      - elasticsearch-logs:/var/log/elasticsearch
    networks:
      pm5net:
        aliases:
          - elasticsearch
  kibana-pm5:
    image: eyp/kibana:5
    build: ./kibana/
    restart: always
    expose:
      - 80
    volumes:
      - kibana-data:/var/lib/kibana
    networks:
      pm5net:
        aliases:
          - kibana
  privateforge-pm5:
    image: eyp/privateforge:5
    build: ./privateforge/
    restart: always
    expose:
      - 8080
    volumes:
      - forge-data:/var/forge/modules
    networks:
      pm5net:
        aliases:
          - privateforge
  master-pm5:
    image: eyp/pupppetmaster:5
    build: ./puppetmaster5
    restart: always
    #[[remote_ip:]remote_port[-remote_port]:]port[/protocol]
    ports:
      - 8141:8140/tcp
    environment:
      - EYP_PUPPETFQDN: 'puppet5'
      - EYP_PM_SSL_REPO: ''
      - EYP_PM_BASE_REPO: ''
    networks:
      pm5net:
        aliases:
          - master
    volumes:
      - pm-conf:/etc/puppetlabs
      - ./ssh:/root/.ssh:ro

volumes:
  forge-data:
  pm-conf:
  elasticsearch-data:
  elasticsearch-logs:
  kibana-data:

networks:
  pm5net:
    driver: bridge
