version: "2.1"
services:
  elasticsearch:
    image: eyp/elasticsearch:5
    build: ./elasticsearch/
    restart: always
    expose:
      - 9200
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch
      - elasticsearch-logs:/var/log/elasticsearch
    networks:
      - pm5net
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
  kibana:
    image: eyp/kibana:5
    build: ./kibana/
    restart: always
    depends_on:
      elasticsearch-pm5:
        condition: service_healthy
    expose:
      - 5601
    volumes:
      - kibana-data:/var/lib/kibana
    networks:
      - pm5net
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5601"]
      interval: 30s
      timeout: 10s
      retries: 5
  puppetmaster:
    image: eyp/pupppetmaster:5
    build: ./puppetmaster5
    restart: always
    depends_on:
      elasticsearch-pm5:
        condition: service_healthy
    #[[remote_ip:]remote_port[-remote_port]:]port[/protocol]
    ports:
      - 8141:8140/tcp
    environment:
      EYP_PUPPETFQDN: 'puppet5'
      EYP_PM_SSL_REPO: ''
      EYP_PM_CUSTOMER_REPO: ''
    networks:
      - pm5net
    volumes:
      - ./ssh:/root/.ssh:ro
      - ./utils:/opt/utils:ro
    healthcheck:
      test: ["CMD", "curl", "--insecure", "https://localhost:8140"]
      interval: 60s
      timeout: 10s
      retries: 10

volumes:
  elasticsearch-data:
  elasticsearch-logs:
  kibana-data:

networks:
  pm5net:
    driver: bridge
